version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - PGHOST=localhost
      - PGUSER=postgres
      - PGPASSWORD=sarvesh#23
      - PGDATABASE=Employeedb
      - PGPORT=5433
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sarvesh#23
      POSTGRES_DB: Employeedb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
